on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      vuln:
        image: vulnerables/web-dvwa
        ports:
          - 80:80
    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: nuclei-templates
        run: wget https://github.com/projectdiscovery/nuclei/releases/download/v2.7.7/nuclei_2.7.7_linux_amd64.zip && unzip nuclei_2.7.7_linux_amd64.zip && ./nuclei -ut
      - name: test
        run: go test -v -timeout 1200s -race ./...